import type { FolderColorKey } from "../constants/folderColors";

export * from "./metadataSearch";

export interface PdfLinkHotspot {
  href: string;
  rect: {
    x: number;
    y: number;
    width: number;
    height: number;
  };
}

export interface SlidePage {
  image_url: string;
  page_number: number;
  width?: number;
  height?: number;
  links?: PdfLinkHotspot[];
}

export interface Deck {
  id: string;
  title: string;
  slug: string;
  file_url: string;
  status: "PENDING" | "CONVERTING" | "PROCESSED" | "DELETED";
  user_id: string;
  display_order: number;
  pages: SlidePage[];
  created_at: string;
  updated_at?: string;
  description?: string;
  file_size?: number;
  require_email?: boolean;
  require_password?: boolean;
  allow_download?: boolean;
  watermark_enabled?: boolean;
  watermark_text?: string | null;
  watermark_status?: "disabled" | "pending" | "processing" | "ready" | "failed";
  is_public?: boolean;
  view_password?: string;
  file_type?: string;
  display_mode?: "raw" | "interactive";
  expires_at?: string | null;
  extracted_text?: string | null;
  thumbnail_url?: string | null;
  page_count?: number | null;
  source_filename?: string | null;
  content_revision?: string;
  investor_note?: string;
  user_handle?: string;
  active_link_count?: number;
  total_link_count?: number;
  deck_link_id?: string;
  unique_visitors?: number;
}

export interface DeckLink {
  id: string;
  deck_id: string;
  link_name: string;
  link_alias: string | null;
  /**
   * Lowercase 32-character hex token generated by the database.
   */
  public_token: string;
  is_enabled: boolean;
  is_primary: boolean;
  created_at: string;
  updated_at: string;
  share_url: string;
}

export interface DeckWithAnalytics extends Deck {
  total_views: number;
  save_count: number;
  last_viewed_at: string | null;
  avg_attention_seconds?: number;
  tags?: LibraryTag[];
}

export interface GlobalTag {
  id: string;
  name: string;
  color: string;
  deleted_at: string | null;
  created_at?: string;
  updated_at?: string | null;
  user_id?: string;
}

export type LibraryTag = GlobalTag;

export interface LibraryFolder {
  id: string;
  name: string;
  color: FolderColorKey;
  tags: LibraryTag[];
  deck_count: number;
  created_at: string;
}

export interface DataRoomFolder {
  id: string;
  data_room_id: string;
  name: string;
  color: string;
  position: string;
  created_by: string;
  updated_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface DataRoomTag extends GlobalTag {
  data_room_id?: string;
}

export interface DataRoomFolderTag {
  folder_id: string;
  tag_id: string;
}

export interface DataRoomDocumentTag {
  document_id: string;
  tag_id: string;
}

export interface DataRoomDocumentSearchSummary {
  id: string;
  deck?: {
    title?: string;
  };
  tags?: DataRoomTag[];
}

export interface DataRoomFolderWithTags extends DataRoomFolder {
  tags: DataRoomTag[];
}

export interface SavedDeckOrganized {
  library_id: string;
  deck_id: string;
  user_id: string;
  folder_id: string | null;
  tags: LibraryTag[];
  saved_at: string;
  last_viewed_at: string | null;
  // Deck metadata
  title: string;
  slug: string;
  file_type?: string;
  status: "PENDING" | "CONVERTING" | "PROCESSED" | "DELETED";
  user_handle: string;
  description: string | null;
  investor_note: string | null;
  // Availability
  is_available: boolean;
  updated_at: string;
}

export interface SavedDataRoomOrganized {
  library_id: string;
  data_room_id: string | null;
  folder_id: string | null;
  tags: LibraryTag[];
  saved_at: string;
  last_viewed_at: string | null;
  title: string;
  slug: string;
  room_handle: string | null;
  room_owner_handle: string | null;
  room_owner_id: string;
  description: string | null;
  investor_note: string | null;
  is_available: boolean;
  is_deleted: boolean;
  expires_at: string | null;
  require_email: boolean;
  require_password: boolean;
  updated_at: string;
}

export type SavedLibraryItemType = "deck" | "data_room";

export interface SavedLibraryItemBase {
  library_id: string;
  item_type: SavedLibraryItemType;
  folder_id: string | null;
  tags: LibraryTag[];
  saved_at: string;
  last_viewed_at: string | null;
  investor_note: string | null;
  title: string;
  description: string | null;
  updated_at: string;
}

export interface SavedDeckLibraryItem extends SavedLibraryItemBase {
  item_type: "deck";
  deck_id: string;
  slug: string;
  user_handle: string;
  file_type?: string;
  status: "PENDING" | "CONVERTING" | "PROCESSED" | "DELETED";
  is_available: boolean;
}

export interface SavedDataRoomLibraryItem extends SavedLibraryItemBase {
  item_type: "data_room";
  data_room_id: string | null;
  slug: string;
  room_handle: string | null;
  room_owner_handle: string | null;
  room_owner_id: string;
  is_available: boolean;
  is_deleted: boolean;
  expires_at: string | null;
  require_email: boolean;
  require_password: boolean;
}

export type SavedLibraryItem =
  | SavedDeckLibraryItem
  | SavedDataRoomLibraryItem;

export interface SavedDeck extends Deck {
  library_id?: string;
  investor_note?: string;
  saved_at: string;
  user_handle: string;
  updated_at: string;
  last_viewed_at: string | null;
}

export interface BrandingSettings {
  id: string;
  user_id: string;
  room_name?: string | null;
  banner_url?: string | null;
  logo_url?: string | null;
  primary_color?: string | null;
  secondary_color?: string | null;
  updated_at?: string | null;
}

export interface DeckPageStats {
  page_number: number;
  total_views: number;
  total_time_seconds: number;
}

export interface DeckLinkStats {
  link_id: string;
  link_name: string;
  link_alias: string | null;
  is_primary: boolean;
  is_enabled: boolean;
  total_views: number;
  unique_visitors: number;
  total_time_seconds: number;
  total_downloads?: number;
  unique_downloaders?: number;
  latest_download_at?: string | null;
  download_conversion?: number;
}

export interface DownloadViewerSummary {
  visitor_id: string;
  viewer_email: string | null;
  total_downloads: number;
  latest_download_at: string;
}

export interface DeckLinkDownloadSummary {
  link_id: string;
  link_name: string;
  link_alias: string | null;
  is_primary: boolean;
  is_enabled: boolean;
  total_downloads: number;
  unique_downloaders: number;
  latest_download_at: string | null;
}

export interface DataRoomDownloadSummary {
  data_room_id: string;
  room_name: string;
  total_downloads: number;
  unique_downloaders: number;
  latest_download_at: string | null;
}

export interface DeckDownloadAnalytics {
  total_downloads: number;
  unique_downloaders: number;
  direct_link_downloads: number;
  data_room_downloads: number;
  links: DeckLinkDownloadSummary[];
  data_rooms: DataRoomDownloadSummary[];
  downloaders: DownloadViewerSummary[];
  downloaders_truncated?: boolean;
}

export interface DocumentDownloadSummary {
  deck_id: string;
  title: string;
  total_downloads: number;
  unique_downloaders: number;
  latest_download_at: string | null;
}

export interface DataRoomDownloadViewerSummary extends DownloadViewerSummary {
  downloaded_documents: DocumentDownloadSummary[];
}

export interface DataRoomDownloadAnalytics {
  total_downloads: number;
  unique_downloaders: number;
  documents: DocumentDownloadSummary[];
  downloaders: DataRoomDownloadViewerSummary[];
  downloaders_truncated?: boolean;
}

export interface TutorialState {
  home_completed?: boolean;
  content_completed?: boolean;
  data_room_completed?: boolean;
  data_room_create_completed?: boolean;
  upload_completed?: boolean;
  workspace_setup_completed?: boolean;
  profile_onboarding_completed?: boolean;
  onboarding_completed?: boolean;
  dashboard_completed?: boolean;
}

export interface OnboardingProfile {
  role?: string | null;
  company_size?: string | null;
  primary_use_case?: string | null;
}

export interface UserProfile {
  id: string;
  full_name: string | null;
  handle: string | null;
  avatar_url: string | null;
  tier: "FREE" | "PRO" | "PRO_PLUS" | "RAISE";
  onboarding_profile?: OnboardingProfile | null;
  tutorial_state?: TutorialState | null;
  updated_at: string | null;
}

export interface DataRoom {
  id: string;
  user_id: string;
  name: string;
  slug: string;
  description?: string;
  icon_url?: string;
  require_email?: boolean;
  require_password?: boolean;
  is_public?: boolean;
  view_password?: string;
  expires_at?: string | null;
  created_at: string;
  updated_at: string;
}

export interface DataRoomDocument {
  id: string;
  data_room_id: string;
  deck_id: string;
  folder_id: string | null;
  folder_name?: string | null;
  display_order: number;
  added_at: string;
  deck?: Deck;
  tags?: DataRoomTag[];
}

export type NotificationType =
  | "deck_view"
  | "deck_save"
  | "signal_threshold"
  | "deck_update"
  | "admin_message";

export interface Notification {
  id: string;
  user_id: string;
  type: NotificationType;
  title: string;
  message: string;
  metadata: Record<string, unknown>;
  read_at: string | null;
  created_at: string;
  expires_at: string;
}

export interface GroupedNotification {
  type: NotificationType;
  date: string; // YYYY-MM-DD
  title: string;
  count: number;
  notifications: Notification[];
}
